const express = require("express");
const app = express();
const server = require("http").Server(app);
const io = require("socket.io")(server);
const next = require("next");
const dev = process.env.NODE_ENV !== "production";
const nextApp = next({ dev });
const handle = nextApp.getRequestHandler();
require("dotenv").config({ path: "./config.env" });
const connectDb = require("./utilsServer/connectDb");
const PORT = process.env.PORT || 3000;
connectDb();

const { addUser, removeUser } = require("./utilsServer/roomActions");

io.on("connection", (socket) => {
  socket.on("join", async ({ userId }) => {
    const users = await addUser(userId, socket.id); //socket.id is generated by socket.io
 
     setInterval(() => {
       socket.emit("connectedUsers", {
         users: users.filter((user) => user.userId !== userId), 
       });
     }, 10000);
  });
});

nextApp.prepare().then(() => {
  // middleware
  app.use(express.json());

  //handle our custom routes
  app.use("/api/signup", require("./api/signup"));
  app.use("/api/auth", require("./api/auth"));
  app.use("/api/search", require("./api/search"));
  app.use("/api/posts", require("./api/posts"));
  app.use("/api/profile", require("./api/profile"));
  app.use("/api/notifications", require("./api/notifications"));
  app.use("/api/chats", require("./api/chats"));
  app.use("/api/reset", require("./api/reset"));

  app.all("*", (req, res) => handle(req, res)); // This code enable files in the pages folder to work properly

  server.listen(PORT, (err) => {
    if (err) throw err;

    console.log(`Express server running on port ${PORT}`);
  });
});
